site:
  name: bot.gorani.me
  site: 'https://bot.gorani.me'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: 토깽이 카카오톡 봇
    template: '%s | 토깽이 카카오톡 봇'
  description: '토깽이는 카카오톡 오픈채팅에서 닉네임 변경 감지, 입·퇴장 알림, 삭제 감지, 자동 공지, 게임, AI 대화까지 제공하는 관리 봇입니다.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 토깽이 카카오톡 봇
    images:
      - url: '~/assets/images/t_main.png'
        width: 1344
        height: 800
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-0MF534BQ8W'

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
